CI: Fix duplicate upload of vcpkg libs
Error: Failed to CreateArtifact: Received non-retryable error:
Failed request: (409) Conflict: an artifact with this name already
exists on the workflow run