CXXTEST: Fix compilation on MSVC This would give an error C4805: '==': unsafe mix of type 'X' and type 'Y' in operation with X=bool and Y=int
This is a reimplentation of commit 25e5e17 for cxxtest-4