GRIM/EMI: Call glViewport for apitrace compatibility
glViewport needs to be called once to avoid the apitrace
error: "could not infer drawable size (glViewport never called)".

This fixes the problem that all apitrace framebuffer pictures
had a default size of 32x32 instead of the correct resolution used
in residualvm.